version: "3.7"
services:
  app:
    build:
      args:
        user: User
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: landing-app
    restart: unless-stopped
    working_dir: /AppServ/www
    volumes:
      - ./:/var/www
    networks:
      - ticket

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/AppServ/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ticket
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - ticket
networks:
  landing:
    driver: bridge